# На 8 пирожков из дрожжевого теста:

## Мука
-- Мука сорго --- 80 г (40%)
-- Мука пшённая --- 80 г (40%)
-- Картофельный крахмал --- 40 г (20%)
-- Разрыхлитель --- 3 г
-- Ксантан --- 6--7 г
-- Псиллиум --- 12 г

Всё смешать.

## Опара + сдоба
-- Тёплая вода --- 200 г
-- Сухие дрожжи --- 3--4 г
-- Мука из общей --- 1 ст. л.
-- Сахар --- 10 г
-- Соль --- 2 г
-- Белок --- 1
-- Ванилин --- на кончике ножа
!! Нужно ещё немного жидкости, грамм 30-50? или дополнительное яйцо/белок

В тёплую воду добавить сахар, соль, муку и дрожжи. 
Мешать до образования пены. 
Немножко подождать.
Добавить ванилин и белок от яйца. 

## Тесто
-- Сливочное масло --- 10 г
-- Растительное масло --- 10 г
-- Уксус --- 1 г (капелька)
+ Мука
+ Опара + сдоба

Сделать воронку в муке.
Добавить опару+сдобу в воронку.
Начать вымешивать.
Когда прримерно 2/3 муки будет замешано, добавить масло и уксус.
Вымешивать тесто минут 10--20, пока тесто не перестанет липнуть к рукам. 
Смазать маслом миску.
Выложить тесто в миску.
Прикрыть миску пищевой плёнкой.
Оставить тесто на час в тёплом месте.
Тесто должно подняться хотя бы в два раза.

## Пирожки
-- Начинка --- 8 * 10 г джема
-- Желток --- 1
-- Мелоко/Вода --- 6 г

Разделить тесто на 8 частей.
Скатать 8 шариков.
Шарики оставить на 10 минут под пищевой плёнкой. 
Каждый шарик немножко помять, формируя диск.
Выложить джем в центр лепёшек.
Закрепить покругу края пирожков в центре.
Выстелить пергаментом противень.
Выложить пирожки швом вниз на противень.
Накрыть пирожки пищевой плёнкой на 20 минут.
Выпекать при температуре 180---200 градусов??? минут 15--30???


# Удачный эксперимент 1
Готовились 20 мин при температуре 180 градусов.
В следующий раз готовить 15 минут при температуре 190 градусов.
Получилось хорошо с 80 г сорго, 80 г рисовой муки, 40 г крахмала тапиоки.
В следующий раз взять 100 г сорго, 60 г рисовой муки, 40 г крахмала тапиоки.
Также нужно больше жидкости. Можно добавть 1 белок или 50 г молока/воды.
Тесто не получилось совсем мягкой консистенции как на видео. Нужно делать диски потолще, чтобы слой теста был больше.
Однако, тесто воздушное, пористое и приятное на вкус.
Замечательно поднялось и было лёгким в обработке.
Ещё минус, что пирожки лопнули и джем немного вытек. Брать меньше начинки.
